### ISSUE TITLE
KAKE

### ISSUE THREAD

**Issue by ShardeOrSerna** [Ticzo/KKK-Kool-Kidz-Klan#1]
det er ingen kake i kjøle skapet

**Comment by Ticzo** [comment]
Sorry, for the inconvience we hope you still remain loyal to the fourth reich, I hope we can solve your problems,for example your life.

**Comment by CrossonroseX** [comment]
![image](https://user-images.githubusercontent.com/51127588/58751234-b7b07600-8461-11e9-9003-d2739d6712d8.png)
